version: '3.8'

services:
  mcp-agent:
    build: .
    container_name: mcp-bugbounty-agent
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mcp-agent-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: mcp-agent-db
    environment:
      POSTGRES_DB: mcp_agent
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
